{ ... }: {
  imports = [
    ./aria2.nix
    ./autojump.nix
    ./bat.nix
    ./bottom.nix
    ./broot.nix
    ./carapace.nix
    ./cava.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./firefox.nix
    ./fish.nix
    ./foot.nix
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./go.nix
    ./gpg.nix
    ./helix.nix
    ./htop.nix
    ./imv.nix
    ./java.nix
    ./joshuto.nix
    ./jq.nix
    ./lazygit.nix
    ./lf.nix
    ./micro.nix
    ./mpv.nix
    ./ncmpcpp.nix
    ./neovim.nix
    ./nix-index.nix
    ./obs.nix
    ./pandoc.nix
    ./password.nix
    ./pistol.nix
    ./pyenv.nix
    ./qutebrowser.nix
    ./ripgrep.nix
    ./rofi.nix
    ./sioyek.nix
    ./sqls.nix
    ./swaylock.nix
    ./texlive.nix
    ./translate.nix
    ./vscode.nix
    ./waybar.nix
    ./wofi.nix
    ./wpaperd.nix
    ./yt-dlp.nix
    ./yazi.nix
    ./zathura.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
