# Use '-K' flag to prompt for sudo password 
# ansible-playbook -K <<filename>>
#####
#####
####### CHANGE VM_IP VARIABLE!!!
#####
#####
---
- name: postinstall common stuff
  hosts: postinstall
  become: yes
  vars:
    username: sam
    vm_ip: "10.10.10.90"
  tasks:
    - name: import docker install file
      import_tasks:
        file: ../tasks/tasks-postinstall-docker.yaml
