# Use '-K' flag to prompt for sudo password
# ansible-playbook -K <<filename>>
---
- name: postinstall common stuff
  hosts: local
  become: yes
  vars:
    username: sam
  tasks:
    - name: copy config files
      ansible.builtin.copy:
        src: configs/
        dest: /home/{{ username }}/
        mode: '0740'
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: import common tasks file
      import_tasks:
        file: ../tasks/tasks-postinstall-common.yaml
