---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- greeting:
    text_size: xl
    text: Minne haluaisit mennä?

#- search:
#    provider: duckduckgo
#    target: _blank
