---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Information-Widgets

- openmeteo:
    label: Siilinjärvi
    latitude: 63.0833
    longitude: 27.6667
    Timezone: Europe/Helsinki
    units: metric
    cache: 5

#- greeting:
#    text_size: xl
#    text: Minne haluaisit mennä?

#- search:
#    provider: duckduckgo
#    target: _blank
