# Use '-K' flag to prompt for sudo password 
# ansible-playbook -K <<filename>>
---
- name: update-upgrade-packages
  apt:
    update_cache: true
    upgrade: safe
- name: install utilities
  apt:
    state: latest
    pkg:
      - nano
      - tree
      - screen
      - htop
      - ssh
      - samba
      - nfs-common #nfs-utils in fedora
      - cifs-utils
      - zsh
- name: add global bash aliases
  blockinfile:
    path: /etc/bash.bashrc
    marker: "# ---ADDED BY ANSIBLE---"
    state: present
    block: |
      alias ..='cd ..'
      alias la='ls -lAhp --group-directories-first --color=auto'
      alias lar='la -R'
      alias docker='sudo docker'
      alias docker-compose='sudo docker-compose'
      alias ip='ip --color'
      alias tree='tree -CF --dirsfirst'
- name: add global zsh aliases
  blockinfile:
    path: /etc/zsh/zshrc
    marker: "# ---ADDED BY ANSIBLE---"
    state: present
    block: |
      alias ..='cd ..'
      alias la='ls -lAhp --group-directories-first --color=auto'
      alias lar='la -R'
      alias docker='sudo docker'
      alias docker-compose='sudo docker-compose'
      alias ip='ip --color'
      alias tree='tree -CF --dirsfirst'
- name: Create a directory /samu
  ansible.builtin.file:
    path: /samu
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0700'
- name: Create symbolic link to /samu
  ansible.builtin.file:
    src: /samu
    dest: /home/{{ username }}/samu
    owner: "{{ username}}"
    group: "{{ username}}"
    state: link

# Set nano to not add lines at end of files
- name: nano config
  blockinfile:
    path: /etc/nanorc
    marker: "# ---ADDED BY ANSIBLE---"
    state: present
    block: |
      set nonewlines
      set autoindent
      set atblanks
      set indicator
      set minibar
      set tabstospaces
      set zap
      set tabsize 4
      bind ^H chopwordleft main
      bind Sh-M-C "{execute}|xsel -ib{enter}{undo}" main
      include /home/{{ username }}/.config/nanorc.d/*.nanorc

- name: change default shell of user to zsh
  become: yes
  command:
    cmd: "chsh -s /usr/bin/zsh {{ username }}"

- name: copy config files
  ansible.builtin.copy:
    src: ../postinstall/configs/
    dest: /home/{{ username }}/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0740'
