version: "3"

networks:
#  vlan10:
#    external: true
  common:
    external: true

services:
#############################
  unifi-controller:
    hostname: unifi-controller
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - MEM_LIMIT=1024
    volumes:
      - /samu/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    networks:
      common:
    restart: unless-stopped
##############################
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /samu/portainer:/data
    networks:
      common:
    ports:
      - "9000:9000"
      - "8000:8000"
    restart: unless-stopped
