# Create new vm with IP of 10.10.10.200
---
- name: install miscellaneous docker services
  hosts: pcloud-debian
  become: yes
  vars:
    - username: sam
    - vm_ip: "10.10.10.130"
    - docker_network_subnet_CIDR: "10.10.10.0/24"
    - docker_network_name: "vlan10"
#    - location_compose_confs: "../compose-files/dockerhost/"

  vars_prompt:
    - name: smb_user
      prompt: Give samba user account, default is
      private: no
      default: "services"
    - name: smb_pswd
      prompt: Give password for samba user
      
  tasks: 
# Install qemu guest agent and configure /etc/interfaces with promisc mode
# This is first because it begins with reboot for system time
###
    - name: import vm tasks file
      import_tasks:
        file: ../tasks/tasks-postinstall-vm.yaml
###
    - name: import common tasks file
      import_tasks:
        file: ../tasks/tasks-postinstall-common.yaml

###
    - name: add cifs/samba details to /etc/fstab
      blockinfile:
        path: /etc/fstab
        marker: "# ---ADDED BY ANSIBLE---"
        state: present
        block: |
          //10.10.10.122/cloud /samu/cloud cifs credentials=/samu/.smb_credentials,uid=1000,gid=1000,rw,iocharset=utf8 0 0
###
# Create folder for samba. Check previous step
    - name: Create a directory for samba (/samu/smb-cloud)
      ansible.builtin.file:
        path: /samu/smb-cloud
        state: directory
        owner: '{{ username }}'
        group: '{{ username }}'
        mode: '0700'

# This is after common tasks because /samu is created now. 
# Also, postinstall docker stuff includes reboot (to activate mount)
    - name: add samba credentials
      blockinfile:
        path: /samu/.smb_credentials
        state: present
        create: yes
        mode: 0000
        owner: root
        group: root
        block: |
          username={{ smb_user }}
          password={{ smb_pswd }}


