version: "3.7"

networks:
  common:
    external: true

services:
#############################
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    hostname: uptime-kuma
    volumes:
      - /samu/uptime-kuma:/app/data
    networks:
      common:
    ports:
      - 3001:3001
    restart: unless-stopped
#############################
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    hostname: swag
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
#      - URL=peikkoluola.com
#      - EXTRA_DOMAINS=samumoila.net, *.samumoila.net
      - URL=samumoila.net
      - EXTRA_DOMAINS=peikkoluola.com, *.peikkoluola.com
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION=30 #how many seconds to wait for dns cert propagation
    volumes:
      - /samu/swag:/config
    networks:
      common:
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
#############################
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    hostname: homepage
    container_name: homepage
    networks:
      common:
    ports:
      - 3000:3000
    volumes:
      - /samu/homepage:/app/config # Make sure your local config directory exists
#      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integration
#      - /samu:/samu:ro #For widget disk info 
    restart: unless-stopped
